### ISSUE TITLE
App Crash in oneplus and some other devices too when leaving the meeting

### ISSUE THREAD

**Issue by Niranjankr0** [mieszko4/react-native-zoom-us#175]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'us.zoom.sdk.InMeetingUserInfo$InMeetingUserRole us.zoom.sdk.InMeetingUserInfo.getInMeetingUserRole()' on a null object reference
       at ch.milosz.reactnative.RNZoomUsModule.sendEvent(RNZoomUsModule.java:1018)
       at ch.milosz.reactnative.RNZoomUsModule.onMyAudioSourceTypeChanged(RNZoomUsModule.java:882)
       at us.zoom.internal.impl.u.a(InMeetingServiceImpl.java:13790)
       at us.zoom.internal.impl.u$1$4.run(InMeetingServiceImpl.java:355)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:245)
       at android.app.ActivityThread.main(ActivityThread.java:8024)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by mieszko4** [comment]
From what I see this could only happen when either of `onMyAudioSourceTypeChanged`, `onUserAudioStatusChanged` or `onUserVideoStatusChanged` got triggered in https://github.com/mieszko4/react-native-zoom-us/blob/master/android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java#L878-L905

**Comment by Niranjankr0** [comment]
In our case we have join the call when tab on  leave the meeting then only app crashing . Might be when we are leaving from meeting then  onUserVideoStatusChanged will called .
And it's not happen on all devices. its happen on oneplus , Samsung  m31 ,MI devices.
let me know is it fixed ?

**Comment by bhavesh0206s** [comment]
Same issue, this is happening only in production.

**Comment by pmogollons** [comment]
@mieszko4 maybe we should check for null in this [line](https://github.com/mieszko4/react-native-zoom-us/blob/d0e57a5ec9b366a41da5bc525d0d010fdc09b8c6/android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java#L1018), that will fix that specific issue.

**Comment by pmogollons** [comment]
@Niranjankr0 can you check this PR and check if it still happens in your app?

**Comment by adeel-ali-atp** [comment]
[Niranjankr0](https://github.com/Niranjankr0) were you able to fix this? I am having same issue.
