### ISSUE TITLE
Zoom initialize app getting crash 

### ISSUE THREAD

**Issue by DineshLt93** [mieszko4/react-native-zoom-us#252]
I have integrated zoom sdk with the below versions.

react-native-zoom-us -- 6.15.0
Whenever initialize the Zoom App got crashes without showing any errors in the debugger. Finally, I checked in the android studio terminal and am getting the below issue.

```
I  providers loaded automaticly
E  BTStateChangeCB is registed
I  Provider GmsCore_OpenSSL not available
W  mkdir failed: EEXIST (File exists) : /data/user/0/com.pkg.test/files
W  remove failed: ENOENT (No such file or directory) : /data/user/0/com.pkg.test/files/conf_process_id
A  /usr/local/google/buildbot/src/android/ndk-release-r20/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type std::bad_cast: std::bad_cast" failed
A  Fatal signal 6 (SIGABRT), code -6 in tid 23183 (pkg.test)
```

**Initialize Code**
      ```await ZoomUs.initialize({
        clientKey: skdKey,
        clientSecret: sdkSecret,
      });```

**JoinMeeting Code**
      
``` 
await ZoomUs.joinMeeting({
        userName: 'Wick',
        apiKey:skdKey,
        meetingNumber: exampleMeeting.meetingNumber,
        password: exampleMeeting.password,
        tk:token,
        signature: source,
      });
```

Please let me know why it happens and give the your inputs to resolve this issue.

**Comment by mieszko4** [comment]
Please try with newest `6.16.5`.

**Comment by DineshLt93** [comment]
Thanks for your effort 
After installing the latest version of zoom SDK can't able open the app getting crash when open the app.

**Comment by mieszko4** [comment]
Perhaps that's related to some additional libs that you use.
Does [test app](https://github.com/mieszko4/react-native-zoom-us-test) work for you?
See something that may be related: https://github.com/mieszko4/react-native-zoom-us/issues/263#issuecomment-1441306683

**Comment by chirag-codealchemy** [comment]
https://github.com/chirag-codealchemy/zoom-test

it's my repo with minimum example app which crashes

note:- my app on crash on devices android 12 and above

**Comment by tunm1228** [comment]
I also got the same error

https://user-images.githubusercontent.com/42457760/229444242-decf51f3-955e-4bc0-99b1-5d6172ccd1d9.MOV

**Comment by tunm1228** [comment]
i downgraded to "react-native-zoom-us" version: "6.15.1" it worked

**Comment by mieszko4** [comment]
Hopefully upgrading Zoom SDK will help (https://github.com/mieszko4/react-native-zoom-us/issues/280)

**Comment by mieszko4** [comment]
Try with 6.18.0 - it uses Android ZoomSDK 5.13.10.

**Comment by mubeenayub1** [comment]
I am trying with 6.18.0. and it's work fine in debug mode and when i create an apk, its crash on meeting screen.

**Comment by mieszko4** [comment]
Please try with react-native-zoom-us@6.20.0 and re-open this issue if you still have a problem.

**Comment by anshuman55a** [comment]
I'm also encountering this issue on my project.
**Error Log**
`java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~-f9H5SYlcXzLMg==/base.apk!/lib/x86_64/libzSdkCore.so"...
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1656)
                                                                                                    	at com.zipow.videobox.sdk.SDKBridge.<clinit>(SDKBridge.java:2)
                                                                                                    	at com.zipow.videobox.sdk.SDKBridge.b(SDKBridge.java:1)
                                                                                                    	at us.zoom.proguard.cm0.v(MeetingSDKModuleService.java:1)
                                                                                                    	at com.zipow.videobox.VideoBoxApplication.initSDKMainboard(VideoBoxApplication.java:8)
                                                                                                    	at com.zipow.videobox.VideoBoxApplication.initAppForSDK(VideoBoxApplication.java:19)
                                                                                                    	at com.zipow.videobox.VideoBoxApplication.onSDKCreated(VideoBoxApplication.java:23)
                                                                                                    	at com.zipow.videobox.VideoBoxApplication.initializeForSDK(VideoBoxApplication.java:55)
                                                                                                    	at us.zoom.internal.impl.e.a(ZoomSDKImpl.java:62)
                                                                                                    	at us.zoom.sdk.ZoomSDK.initialize(ZoomSDK.java:1)
                                                                                                    	at ch.milosz.reactnative.RNZoomUsModule$3.run(RNZoomUsModule.java:194)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)`
                                                                                                    	
**React-Native version: 0.68.5
Library version: react-native-zoom-us@6.20.0
Zoom SDK version : 5.16.2.16555
Android OS version: 14**

**Request:**
If any solution is available, please let me know at the earliest.

**Comment by mieszko4** [comment]
New issue created -> https://github.com/mieszko4/react-native-zoom-us/issues/358
