### ISSUE TITLE
Android crash when joining meeting even after upgrading to 0.72

### ISSUE THREAD

**Issue by frankie-fk** [mieszko4/react-native-zoom-us#303]
Hi, weird stuff that even though I upgrade from RN 0.68.2 to 0.72.2, but still:
- Crashes are seen when joining meeting on Android.
- Work well on iOS (even in 0.68.2)
- I cloned the react-native-zoom-test and it runs well on both Android (0.72.2) and iOS.
- I check all the configuration/gradle. All the same like the example project.
My I ask why this happens? Is there something else going on that's not about RN version? Like the packagingOptions?

**Comment by frankie-fk** [comment]
Ok, so I checked the logcat and this is the error log:
`E  FATAL EXCEPTION: main
                                                                                                    Process: com.cysterhood, PID: 27772
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cysterhood/com.zipow.videobox.ConfActivityNormal}: android.view.InflateException: Binary XML file line #16 in com.cysterhood:layout/zm_conf_main_screen: Binary XML file line #16 in com.cysterhood:layout/zm_conf_main_screen: Error inflating class com.zipow.videobox.newjoinflow.waitingview.oldui.ZmOldUINewJoinFlowWaitingView
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3644)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3781)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7918)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #16 in com.cysterhood:layout/zm_conf_main_screen: Binary XML file line #16 in com.cysterhood:layout/zm_conf_main_screen: Error inflating class com.zipow.videobox.newjoinflow.waitingview.oldui.ZmOldUINewJoinFlowWaitingView
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #16 in com.cysterhood:layout/zm_conf_main_screen: Error inflating class com.zipow.videobox.newjoinflow.waitingview.oldui.ZmOldUINewJoinFlowWaitingView
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
                                                                                                    	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:476)
                                                                                                    	at android.app.Activity.setContentView(Activity.java:3602)
                                                                                                    	at androidx.activity.ComponentActivity.setContentView(ComponentActivity.java:403)
                                                                                                    	at com.zipow.videobox.ConfActivityNormal.onCreate(ConfActivityNormal.java:37)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8342)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8321)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3625)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3781)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7918)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
2023-09-28 12:02:17.585 27772-27772 AndroidRuntime          com.cysterhood                       E  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/Player$Listener;
                                                                                                    	... 30 more
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.Player$Listener" on path: DexPathList[[zip file "/data/app/~~014TqHgKbceNuqvLEqEnlA==/com.cysterhood-2ZBSY--XY5nTQFMsoOmsRg==/base.apk"],nativeLibraryDirectories=[/data/app/~~014TqHgKbceNuqvLEqEnlA==/com.cysterhood-2ZBSY--XY5nTQFMsoOmsRg==/lib/arm64, /data/app/~~014TqHgKbceNuqvLEqEnlA==/com.cysterhood-2ZBSY--XY5nTQFMsoOmsRg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	... 30 more
`

**Comment by frankie-fk** [comment]
found out the issue. That's due to the react-native-video package.
- Even though I have exclude exo-player in build.gradle. However, the latest exo-player in "react-native-video: ^5.2.1" is still old version. Upgrade it to alpha's latest version solves the issue.
