### ISSUE TITLE
Android App crash when start the meeting

### ISSUE THREAD

**Issue by MalikMati98** [mieszko4/react-native-zoom-us#322]
Hi, when start the zoom meeting android app is crash.
 ZoomUs.startMeeting({
        userName: userFullName,
        meetingNumber: meetingId,
        userId: meetingSignature, // ios only field
        zoomAccessToken: startUrl.split('=')[1],
        userType: 2, // optional
      })
i checked all the values are correct and it working fine on iOS
 "react-native-zoom-us": "^6.18.1",
   "react": "18.2.0",
    "react-native": "0.72.3"
    **Here is the error**
`FATAL EXCEPTION: main
Process: com.steaminventors.app, PID: 2150
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.steaminventors.app/com.zipow.videobox.ConfActivityNormal}: android.view.InflateException: Binary XML file line #16 in com.steaminventors.app:layout/zm_conf_main_screen: Binary XML file line #16 in com.steaminventors.app:layout/zm_conf_main_screen: Error inflating class com.zipow.videobox.newjoinflow.waitingview.oldui.ZmOldUINewJoinFlowWaitingView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3835)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4011)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: android.view.InflateException: Binary XML file line #16 in com.steaminventors.app:layout/zm_conf_main_screen: Binary XML file line #16 in com.steaminventors.app:layout/zm_conf_main_screen: Error inflating class com.zipow.videobox.newjoinflow.waitingview.oldui.ZmOldUINewJoinFlowWaitingView
Caused by: android.view.InflateException: Binary XML file line #16 in com.steaminventors.app:layout/zm_conf_main_screen: Error inflating class com.zipow.videobox.newjoinflow.waitingview.oldui.ZmOldUINewJoinFlowWaitingView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:541)
	at android.app.Activity.setContentView(Activity.java:3525)
	at androidx.activity.ComponentActivity.setContentView(ComponentActivity.java:433)
	at com.zipow.videobox.ConfActivityNormal.onCreate(ConfActivityNormal.java:37)
	at android.app.Activity.performCreate(Activity.java:8207)
	at android.app.Activity.performCreate(Activity.java:8191)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3808)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4011)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: android.view.InflateException: Binary XML file line #120 in com.steaminventors.app:layout/zm_new_waiting_join_view: Binary XML file line #120 in com.steaminventors.app:layout/zm_new_waiting_join_view: Error inflating class com.zipow.videobox.newjoinflow.waitingview.oldui.ZmJoinFlowVideoView
Caused by: android.view.InflateException: Binary XML file line #120 in com.steaminventors.app:layout/zm_new_waiting_join_view: Error inflating class com.zipow.videobox.newjoinflow.waitingview.oldui.ZmJoinFlowVideoView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at android.view.View.inflate(View.java:28552)
	at com.zipow.videobox.newjoinflow.waitingview.oldui.ZmOldUINewJoinFlowWaitingView.a(ZmOldUINewJoinFlowWaitingView.java:7)
	at com.zipow.videobox.newjoinflow.waitingview.oldui.ZmOldUINewJoinFlowWaitingView.<init>(ZmOldUINewJoinFlowWaitingView.java:53)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:541)
	at android.app.Activity.setContentView(Activity.java:3525)
	at androidx.activity.ComponentActivity.setContentView(ComponentActivity.java:433)
	at com.zipow.videobox.ConfActivityNormal.onCreate(ConfActivityNormal.java:37)
	at android.app.Activity.performCreate(Activity.java:8207)
	at android.app.Activity.performCreate(Activity.java:8191)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3808)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4011)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: android.view.InflateException: Binary XML file line #36 in com.steaminventors.app:layout/zm_new_joinflow_video: Binary XML file line #36 in com.steaminventors.app:layout/zm_new_joinflow_video: Error inflating class com.google.android.exoplayer2.ui.PlayerView
Caused by: android.view.InflateException: Binary XML file line #36 in com.steaminventors.app:layout/zm_new_joinflow_video: Error inflating class com.google.android.exoplayer2.ui.PlayerView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at android.view.View.inflate(View.java:28552)
	at com.zipow.videobox.newjoinflow.waitingview.oldui.ZmJoinFlowVideoView.a(ZmJoinFlowVideoView.java:1)
	at com.zipow.videobox.newjoinflow.waitingview.oldui.ZmJoinFlowVideoView.<init>(ZmJoinFlowVideoView.java:55)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at android.view.View.inflate(View.java:28552)
	at com.zipow.videobox.newjoinflow.waitingview.oldui.ZmOldUINewJoinFlowWaitingView.a(ZmOldUINewJoinFlowWaitingView.java:7)
	at com.zipow.videobox.newjoinflow.waitingview.oldui.ZmOldUINewJoinFlowWaitingView.<init>(ZmOldUINewJoinFlowWaitingView.java:53)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:541)
	at android.app.Activity.setContentView(Activity.java:3525)
	at androidx.activity.ComponentActivity.setContentView(ComponentActivity.java:433)
	at com.zipow.videobox.ConfActivityNormal.onCreate(ConfActivityNormal.java:37)
	at android.app.Activity.performCreate(Activity.java:8207)
	at android.app.Activity.performCreate(Activity.java:8191)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3808)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4011)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.ClassCastException: androidx.media3.ui.AspectRatioFrameLayout cannot be cast to com.google.android.exoplayer2.ui.AspectRatioFrameLayout
	at com.google.android.exoplayer2.ui.PlayerView.<init>(PlayerView.java:404)
	at com.google.android.exoplayer2.ui.PlayerView.<init>(PlayerView.java:324)
	... 63 more`

**Comment by MalikMati98** [comment]
Yes, but i created new app for this and it working fine

**Comment by MalikMati98** [comment]
Hi, @frankie-fk  issue is resolved you’re right when i installed new version of react-native-video library its works. Thanks

**Comment by Dilnawazkhan4Saufik** [comment]
Hey @MalikMati98  if you are using "react-native-video" then make sure you update this library to latest version which is
 "react-native-video": "^5.2.1"
 the error will resolve
