### ISSUE TITLE
app cresh when click on chat button.

### ISSUE THREAD

**Issue by nguptaesaral** [mieszko4/react-native-zoom-us#327]
The application functions properly, but when attempting to initiate a chat by clicking on the chat button, the application crashes immediately. I attempted to diagnose the issue using Android Studio, and it generated the following error.

`FATAL EXCEPTION: main
                                                                                                    Process: com.zoomsdk, PID: 10864
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lio/reactivex/disposables/CompositeDisposable;
                                                                                                    	at us.zoom.zmsg.fragment.MMChatInputFragment.<init>(MMChatInputFragment.java:224)
                                                                                                    	at us.zoom.proguard.l83.<init>(ZmMeetingChatInputFragment.java:1)
                                                                                                    	at us.zoom.proguard.p93.<init>(ZmMeetingNormalChatInputFragment.java:1)
                                                                                                    	at com.zipow.videobox.conference.service.ZmMeetingServiceImpl.createChatInputFragment(ZmMeetingServiceImpl.java:15)
                                                                                                    	at us.zoom.proguard.a83.a(ZmMeetMsgNavHelper.java:27)
                                                                                                    	at us.zoom.proguard.hm0.U(MeetingThreadsFragment.java:50)
                                                                                                    	at us.zoom.proguard.xh0.onCreateView(MMThreadsFragment.java:26)
                                                                                                    	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
                                                                                                    	at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:492)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
                                                                                                    	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:248)
                                                                                                    	at us.zoom.uicommon.activity.ZMActivity.onStart(ZMActivity.java:5)
                                                                                                    	at com.zipow.videobox.SimpleInMeetingActivity.onStart(SimpleInMeetingActivity.java:1)
                                                                                                    	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1543)
                                                                                                    	at android.app.Activity.performStart(Activity.java:8330)
                                                                                                    	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3670)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "io.reactivex.disposables.CompositeDisposable" on path: DexPathList[[zip file "/data/app/~~pDPTfXEycmHf7xWONFhGkA==/com.zoomsdk-6MMBCS_uPKPcYpRiX7YNmA==/base.apk"],nativeLibraryDirectories=[/data/app/~~pDPTfXEycmHf7xWONFhGkA==/com.zoomsdk-6MMBCS_uPKPcYpRiX7YNmA==/lib/x86_64, /data/app/~~pDPTfXEycmHf7xWONFhGkA==/com.zoomsdk-6MMBCS_uPKPcYpRiX7YNmA==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at us.zoom.zmsg.fragment.MMChatInputFragment.<init>(MMChatInputFragment.java:224) 
                                                                                                    	at us.zoom.proguard.l83.<init>(ZmMeetingChatInputFragment.java:1) 
                                                                                                    	at us.zoom.proguard.p93.<init>(ZmMeetingNormalChatInputFragment.java:1) 
                                                                                                    	at com.zipow.videobox.conference.service.ZmMeetingServiceImpl.createChatInputFragment(ZmMeetingServiceImpl.java:15) 
                                                                                                    	at us.zoom.proguard.a83.a(ZmMeetMsgNavHelper.java:27) 
                                                                                                    	at us.zoom.proguard.hm0.U(MeetingThreadsFragment.java:50) 
                                                                                                    	at us.zoom.proguard.xh0.onCreateView(MMThreadsFragment.java:26) 
                                                                                                    	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995) 
                                                                                                    	at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:492) 
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523) 
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261) 
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840) 
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758) 
                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701) 
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849) 
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784) 
                                                                                                    	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262) 
                                                                                                    	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478) 
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:248) 
                                                                                                    	at us.zoom.uicommon.activity.ZMActivity.onStart(ZMActivity.java:5) 
                                                                                                    	at com.zipow.videobox.SimpleInMeetingActivity.onStart(SimpleInMeetingActivity.java:1) 
                                                                                                    	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1543) 
                                                                                                    	at android.app.Activity.performStart(Activity.java:8330) 
                                                                                                    	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3670) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) `

it looks like it is the issue of proguard, but i don't enabled the proguard in my application. i am using the following configuration

`  "dependencies": {
    "jsrsasign": "^10.9.0",
    "jsrsasign-util": "^1.0.5",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-zoom-us": "^6.19.4"
  },`

Please let me know if any suggestion.
Thanks in advance.

**Comment by wilkinson4** [comment]
I am also experiencing the crash. @mieszko4 The app is crashing with the following error:
```
java.lang.NoClassDefFoundError: Failed resolution of: Lio/reactivex/disposables/CompositeDisposable;
                                                                                                    	at us.zoom.zmsg.fragment.MMChatInputFragment.<init>(MMChatInputFragment.java:224)
                                                                                                    	at us.zoom.proguard.l83.<init>(ZmMeetingChatInputFragment.java:1)
                                                                                                    	at us.zoom.proguard.p93.<init>(ZmMeetingNormalChatInputFragment.java:1)
```
I'm am currently stuck on trying to fix it. Any ideas? I don't think it's a proguard issue.

**Comment by nguptaesaral** [comment]
Hi @wilkinson4,

I have successfully identified the root cause of the issue. It appears that a crucial library, namely 'reactivex', is absent. To rectify this, kindly include the following dependency in the gradle.build file:

`    implementation 'io.reactivex.rxjava2:rxjava:2.1.13'
`

Thanks

**Comment by wilkinson4** [comment]
> Hi @wilkinson4,
> 
> I have successfully identified the root cause of the issue. It appears that a crucial library, namely 'reactivex', is absent. To rectify this, kindly include the following dependency in the node_modules\react-native-zoom-us\android\build.gradle -> dependencies :
> 
> ` implementation 'io.reactivex.rxjava2:rxjava:2.1.13'`
> 
> Thanks

That did it! PR is up. Thank you!
