### ISSUE TITLE
App Crashes on click of reaction and More button on version 6.19.6

### ISSUE THREAD

**Issue by satyamtothenew** [mieszko4/react-native-zoom-us#334]
App Crash when user click on reaction and more button in a meeting after upgrading to 6.19.6 

<img width="409" alt="image" src="https://github.com/mieszko4/react-native-zoom-us/assets/133632982/ac2bdc1d-3bcf-4ace-94aa-0dc506fc9d49">

Native Stack trace: 
FATAL EXCEPTION: main
java.lang.IllegalAccessError: Method 'void androidx.activity.ComponentDialog.onStart()' is inaccessible to class 'us.zoom.proguard.sp1' (declaration of 'us.zoom.proguard.sp1' appears in classes13.dex)
at us.zoom.proguard.sp1.onStart(ZMBaseBottomSheetDialog.java:1)
at android.app.Dialog.show(Dialog.java:333)
at androidx.fragment.app.DialogFragment.onStart(DialogFragment.java:710)
                                                                                                    

    "react-native": "0.67.3",
    "react-native-zoom-us": "6.19.6",

**Comment by satyamtothenew** [comment]
The issue because of appCombat version was low so material dialog library was crashing
the issue is fixed once i increased 0.68 and make appcombat increases.
