### ISSUE TITLE
JoinMeeting crashes the app android

### ISSUE THREAD

**Issue by anshuman55a** [mieszko4/react-native-zoom-us#358]
When I call join Meeting the app instantly crashes but it works fine in ios.

**Error Log**
`java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~-f9H5SYlcXzLMg==/base.apk!/lib/x86_64/libzSdkCore.so"...
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1656)
                                                                                                    	at com.zipow.videobox.sdk.SDKBridge.<clinit>(SDKBridge.java:2)
                                                                                                    	at com.zipow.videobox.sdk.SDKBridge.b(SDKBridge.java:1)
                                                                                                    	at us.zoom.proguard.cm0.v(MeetingSDKModuleService.java:1)
                                                                                                    	at com.zipow.videobox.VideoBoxApplication.initSDKMainboard(VideoBoxApplication.java:8)
                                                                                                    	at com.zipow.videobox.VideoBoxApplication.initAppForSDK(VideoBoxApplication.java:19)
                                                                                                    	at com.zipow.videobox.VideoBoxApplication.onSDKCreated(VideoBoxApplication.java:23)
                                                                                                    	at com.zipow.videobox.VideoBoxApplication.initializeForSDK(VideoBoxApplication.java:55)
                                                                                                    	at us.zoom.internal.impl.e.a(ZoomSDKImpl.java:62)
                                                                                                    	at us.zoom.sdk.ZoomSDK.initialize(ZoomSDK.java:1)
                                                                                                    	at ch.milosz.reactnative.RNZoomUsModule$3.run(RNZoomUsModule.java:194)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)`
                                                                                                    	
**React-Native version: 0.68.5
Library version: react-native-zoom-us@6.20.0
Zoom SDK version : 5.16.2.16555
Android OS version: 14**

**Request:**
If any solution is available, please let me know at the earliest.

**Comment by anshuman55a** [comment]
@mieszko4 Please look into this

**Comment by farzans** [comment]
@mieszko4 We are also facing the same issue. Appreciate if you can support.

**Comment by mieszko4** [comment]
I am not sure why it happens for you. But I see that you do not use the newest version.

Could you try with 8.0.1 version? Also try with [test app](https://github.com/mieszko4/react-native-zoom-us-test).

**Comment by mieszko4** [comment]
Works for me with 12.0.0
