### ISSUE TITLE
Android app crash when joining a meeting

### ISSUE THREAD

**Issue by ajengrf** [mieszko4/react-native-zoom-us#52]
Hi, my android app crash when joining the meeting. I use the latest version of react-navigation and start a new project but it isn't working on android (it is working on iOS). This is the version of packages that I use:
"@react-navigation/native": "^5.8.10",
"@react-navigation/stack": "^5.12.8",
"react-native-zoom-us": "^5.3.4"

Please I need your support, do I need to change or add some configuration to use this package with the latest version of react-navigation?

**Comment by mieszko4** [comment]
It is hard to know the reason without any log.
Perhaps you could check some logs and paste here?
Also maybe this issue will help you https://github.com/mieszko4/react-native-zoom-us/issues/51?

**Comment by ajengrf** [comment]
Hi, this is the logcat after successfully initialize the zoom meeting

```
2021-01-12 08:04:34.975 6674-6674/com.testzoom D/CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10153; state: DISABLED
2021-01-12 08:04:35.061 6674-6762/com.testzoom I/ReactNativeJS: { initializeResult: 'Already initialize Zoom SDK successfully.' }
2021-01-12 08:04:41.701 6674-6762/com.testzoom I/ReactNativeJS: You can use the camera
2021-01-12 08:04:45.672 6674-6762/com.testzoom I/ReactNativeJS: join
2021-01-12 08:04:45.681 6674-6763/com.testzoom I/MeetingService: joinMeetingWithParams: sUri=zoomus://zoom.us/join?confno=123123&uname=ajeng&pwd=hsehwe123&show_water_mark=1&meeting_views_options=0&invite_options=255&zc=0
2021-01-12 08:04:45.693 6674-6763/com.testzoom I/RNZoomUs: joinMeeting, joinMeetingResult=0
2021-01-12 08:04:45.793 6674-6674/com.testzoom W/Settings: Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
2021-01-12 08:04:45.837 6674-6674/com.testzoom D/CompatibilityChangeReporter: Compat change id reported: 147600208; UID 10153; state: ENABLED
2021-01-12 08:04:46.000 6674-6674/com.testzoom W/Settings: Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
2021-01-12 08:04:46.848 6674-6674/com.testzoom D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2021-01-12 08:04:46.849 6674-6674/com.testzoom E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.testzoom, PID: 6674
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/localbroadcastmanager/content/LocalBroadcastManager;
        at com.zipow.videobox.ConfActivityNormal.registerSdkBroadcast(ConfActivityNormal.java:5375)
        at com.zipow.videobox.ConfActivityNormal.onResume(ConfActivityNormal.java:1280)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
        at android.app.Activity.performResume(Activity.java:8135)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4434)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.localbroadcastmanager.content.LocalBroadcastManager" on path: DexPathList[[zip file "/data/app/~~9Wfyw69BXbJB_D-l4aTk1g==/com.testzoom-3oe5G9poZlhiAC6NtHplgA==/base.apk"],nativeLibraryDirectories=[/data/app/~~9Wfyw69BXbJB_D-l4aTk1g==/com.testzoom-3oe5G9poZlhiAC6NtHplgA==/lib/x86, /data/app/~~9Wfyw69BXbJB_D-l4aTk1g==/com.testzoom-3oe5G9poZlhiAC6NtHplgA==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.zipow.videobox.ConfActivityNormal.registerSdkBroadcast(ConfActivityNormal.java:5375) 
        at com.zipow.videobox.ConfActivityNormal.onResume(ConfActivityNormal.java:1280) 
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456) 
        at android.app.Activity.performResume(Activity.java:8135) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4434) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
2021-01-12 08:04:46.874 6674-6674/com.testzoom I/Process: Sending signal. PID: 6674 SIG: 9

```

**Comment by ajengrf** [comment]
I manage to find a solution for this, just add this dependency into `android/app/build.gradle` and it works for me.

```
implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'
```

Thank you for your help, I'm closing this issue😆

**Comment by mieszko4** [comment]
Ok, great! It is strange that you had to include `localbroadcastmanager`. In the example app (https://github.com/mieszko4/react-native-zoom-us-test) I did not have to do that.

Also for reference, this may be related: https://devforum.zoom.us/t/zoom-sdk-failed-to-initizilation-error-1-internalerror-code-0/12374/16
