### ISSUE TITLE
(android) RNZoomUsModule.initialize issue

### ISSUE THREAD

**Issue by zvs001** [mieszko4/react-native-zoom-us#98]
Seems something is broken for android. 
Reproduced on v5.12.0.
I think it was ok on v5.3.4.

I received a lot of reports about (probably crashes):

```
java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Promise.reject(java.lang.String, java.lang.Throwable)' on a null object reference         
 at ch.milosz.reactnative.RNZoomUsModule.initialize(RNZoomUsModule.java:126)        
 at java.lang.reflect.Method.invoke(Method.java:-2)        
 at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)        
 at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)       
 at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java:-2)        
 at android.os.Handler.handleCallback(Handler.java:938)         
 at android.os.Handler.dispatchMessage(Handler.java:99)         
 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)           
 at android.os.Looper.loop(Looper.java:246)         
 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)     
 at java.lang.Thread.run(Thread.java:923)

```

**Comment by mieszko4** [comment]
Fixed in `v5.12.1`
